### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jokereven** [FlareZone/FlareZone#104]
- [ ] trending 页面下面加载是显示骨架 [skeleton](https://chakra-ui.com/docs/components/skeleton/usage)

**Comment by jokereven** [comment]
- [ ] when i trending end show to the top.

**Comment by jokereven** [comment]
- [ ] switch mode.

**Comment by jokereven** [comment]
- [ ] notification

**Comment by jokereven** [comment]
- [ ] mill use data fetch.

**Comment by jokereven** [comment]
- [ ] wallet show more detail data.

**Comment by jokereven** [comment]
- [ ] do post can update image, and let markdown render more will.

**Comment by jokereven** [comment]
- [ ] account page link to status page.

**Comment by jokereven** [comment]
- [ ] 页面细节优化

**Comment by jokereven** [comment]
- [ ] 评论页面

**Comment by jokereven** [comment]
- [ ] trending 的 Popular Authors  加载太久. [Popular Authors](https://flare-zone-l2x0pvwl2-flare-zone.vercel.app/explore?vercelThreadId=ivW7o)

**Comment by jokereven** [comment]
![image](https://github.com/FlareZone/FlareZone/assets/73232691/82f25b11-022f-452b-a768-369d72fcb46d)
trending 页面的显示并不是同一时间显示，可能请求数据得优化.

**Comment by jokereven** [comment]
d

> 

并没有出来优化，只是处理了怎么展示.

**Comment by jokereven** [comment]
![image](https://github.com/FlareZone/FlareZone/assets/73232691/6cbafd91-70cc-4c1e-9704-fb6e3a44e4e0)
- [ ] 页面变窄之后有滚动条.

**Comment by jokereven** [comment]
![image](https://github.com/FlareZone/FlareZone/assets/73232691/0b49dba8-3a4c-4cc5-b2af-6d7fbd853f7c)
- [ ] mill 的布局.

**Comment by jokereven** [comment]
- [ ] account show

**Comment by jokereven** [comment]
> * [ ]  account show

加上加载骨架

**Comment by jokereven** [comment]
> > * [ ]   account show
> 
> 加上加载骨架

![image](https://github.com/FlareZone/FlareZone/assets/73232691/9701c440-6954-4ea4-ae22-7bbe015cd018)
先加一个基础骨架

**Comment by jokereven** [comment]
![image](https://github.com/FlareZone/FlareZone/assets/73232691/c5eda502-ca12-4626-b7a9-b5b7e91e4aa8)
- [ ] 切换模式 Popular Authors 发生了改变.
